### ISSUE TITLE
Adwaita in some windows in the Cinnamon DE

### ISSUE THREAD

**Issue by ZK9RX6** [dracula/gtk#140]
Well, first of all, I would like to congratulate you on the Dracula GTK theme, which is excellent.

Second, I would like to report a bug in the Cinnamon DE. Some windows appear with the Adwaita theme (e.g. login window, driver manager, grub customizer, and others).

I am using Linux Mint 20.2 Cinnamon (this bug is also present when using the XFCE version).

![DRACULA-GTK-BUG](https://user-images.githubusercontent.com/5471260/131594311-02861bb2-ef52-43ae-914d-abe50c8369fa.png)

**Comment by mebesus** [comment]
I think you've installed this theme locally, in `~/.themes`, right? Whenever you run an application using `su` or `sudo`, the application looks for the GTK theme in `/usr/share/themes` rather than both `/usr/share/themes` and `~/.themes`. So what can you do now? Move this theme from `~/.themes` from `/usr/share/themes`. I hope this fixes this issue
