### ISSUE TITLE
Gnome Shell 42

### ISSUE THREAD

**Issue by xukashi** [dracula/gtk#184]
unfortunately there are a few problems with the gnome shell 42.
![Bildschirmfoto vom 2022-04-20 14-58-32](https://user-images.githubusercontent.com/301051/164236518-2294570a-5c2d-4985-91ae-7b5516069290.png)
![Bildschirmfoto vom 2022-04-20 15-03-37](https://user-images.githubusercontent.com/301051/164236762-a03225bd-4754-491f-b349-f0f7c9e48780.png)
![Bildschirmfoto vom 2022-04-20 15-04-14](https://user-images.githubusercontent.com/301051/164236775-693dbbfa-43c9-4837-8297-de89572ae770.png)

**Comment by hrvdm** [comment]
![image](https://user-images.githubusercontent.com/66192048/165187446-d949d8c3-3941-4a5f-a97e-e2a5ba83d991.png)

Yeah; I have this on menus with GS42

**Comment by AleCo3lho** [comment]
Same situation here guys.
![image](https://user-images.githubusercontent.com/20954739/165578661-9e8408f4-831d-488d-82cb-80fd74909b10.png)
 Also gnome 42

**Comment by elihpoivulp** [comment]
![image](https://user-images.githubusercontent.com/45350234/165707729-fcdcc2c1-7ccc-43b2-a797-042d0390980d.png)
Gnome version 42

**Comment by sellth** [comment]
The reason is a fundamental change in how theming is supported by Gnome: https://blogs.gnome.org/alatiera/2021/09/18/the-truth-they-are-not-telling-you-about-themes/

Basically, GTK themes are in the process of being removed and (some) of the Gnome applications stopped complying with them. All theming now has to take place in `~/.config/gtk.css` which maybe warrants a separate Gnome repository, as technically it's not about theming GTK any more.

https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1.1/index.html

**Comment by hexdecimal16** [comment]
also using this theme is causing this bug https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1970148

**Comment by aquatix** [comment]
It's true that GTK themes are changing/disappearing, but the issues shown in this ticket are in gnome-shell. Maybe you could look into these anyway? I've seen a few other themes fixing shell issues at least, and it would be great to keep on using this fine theme :)

**Comment by EliverLara** [comment]
Hi, I fixed some of the visual issues with gnome-shell-v42, it would be great if you could test it and report back if you find any other issues.

**Comment by BillyBlaze** [comment]
Thanks @EliverLara it looks good, I have found one more issue with 'Dash to Dock' (version 71). Other shells do not have this issue

![image](https://user-images.githubusercontent.com/445608/168296264-89df65f5-6f2e-4250-a616-c38d5d80e97d.png)

**Comment by P3R4R4** [comment]
It also seems like dracula theme doesn't work on gnome control center. The button are not themed. I don't know if it is theme's error or the others. I'm using on manjaro and after system update, this happened.

![image](https://user-images.githubusercontent.com/104021043/168325704-2214ba38-3811-4612-a1db-486cc47d348c.png)

**Comment by ran-dall** [comment]
@BillyBlaze, I sent a PR to fix Dash to Dock. #190

**Comment by EliverLara** [comment]
@BillyBlaze Are you sure you're using the right version of the theme provided [here](https://github.com/dracula/gtk/blob/master/gnome-shell/v40/gnome-shell.css) ?

@P3R4R4 this is a conflict with libadwaita, but [this](https://github.com/odziom91/libadwaita-theme-changer) works as a temporary solution.

**Comment by EliverLara** [comment]
@BillyBlaze Are you sure you're using the right version of the theme provided [here](https://github.com/dracula/gtk/blob/master/gnome-shell/v40/gnome-shell.css) ?

@P3R4R4 this is a conflict with libadwaita, but [this](https://github.com/odziom91/libadwaita-theme-changer) works as a temporary solution.

**Comment by ran-dall** [comment]
> Are you sure you're using the right version of the theme provided [here](https://github.com/dracula/gtk/blob/master/gnome-shell/v40/gnome-shell.css?rgh-link-date=2022-05-19T19%3A22%3A48Z) ?

@EliverLara The problem isn't the version of the theme. The theme has no support for Dash to Dock, which I added preliminary support in #190. The theming for Dash to Dock is documented [here](https://micheleg.github.io/dash-to-dock/theming.html).

> [this](https://github.com/odziom91/libadwaita-theme-changer) is a conflict with libadwaita, but this works as a temporary solution.

It requires Python 3.10, which is probably not deployed on most systems unless they're using a rolling distro. I think most still default to 3.9 or 3.8. Perhaps I can contribute a bash script specific for Dracula that does the same thing with a much smaller footprint.

**Comment by EliverLara** [comment]
@ran-dall 

> The problem isn't the version of the theme. The theme has no support for Dash to Dock, which I added preliminary support in https://github.com/dracula/gtk/pull/190. The theming for Dash to Dock is documented [here](https://micheleg.github.io/dash-to-dock/theming.html).

I was guessing it could be related to the theme version since I can't reproduce the issue in a fresh ubuntu 22.04 installation, this is how it looks:

With the right theme version: 

![Captura de pantalla de 2022-05-19 14-57-51](https://user-images.githubusercontent.com/9838260/169395506-3b8e94e3-a17e-4cd9-afe5-4470806f94ff.png)

With the wrong theme version: 

![Captura de pantalla de 2022-05-19 14-59-58](https://user-images.githubusercontent.com/9838260/169395519-f9ef7f93-0602-49af-9b04-7dda2bba781c.png)

**Comment by ran-dall** [comment]
@EliverLara Interesting. If I'm reading the theme right (and taking the GNOME specification and Dash to Dock docs into account), the background color (and related settings) SHOULD be applied to the dock, because technically it's applying the settings to the dashboard, in general...and the dock is technically styled as part of the dashboard. I believe that Dash to Dock's solution to GNOME's theming is to allow you to (in a way) sidestep out of this inheritance.

**Comment by ran-dall** [comment]
That said, I know Ubuntu is trying to be more purist in its utilization of GNOME; however, I wonder if maybe there's more to it than that? I'm using Gentoo and LFS. I'm running 41/42, with my own icon theme that I'll be upstreaming to you soon (https://github.com/vinceliuice/Tela-circle-icon-theme/pull/85).

![image](https://user-images.githubusercontent.com/17261190/169413308-7d831102-9820-403a-b1ba-f3670be1d390.png)

**Comment by ran-dall** [comment]
@EliverLara Hey brother, I pulled down the branch, and yeah, it's looking good. The only thing I see is the corners; as the theme is still forcing the square corners, instead of what you have set.

My PR
![image](https://user-images.githubusercontent.com/17261190/170512319-1b388575-9510-4d68-baf3-de51f51b7084.png)

Your Branch
![image](https://user-images.githubusercontent.com/17261190/170512453-aa42a5a2-12e7-4002-95e7-96b01c4c6f67.png)

**Comment by ran-dall** [comment]
https://github.com/dracula/gtk/issues/188#issuecomment-1145184325

**Comment by xukashi** [comment]
> That said, I know Ubuntu is trying to be more purist in its utilization of GNOME; however, I wonder if maybe there's more to it than that? I'm using Gentoo and LFS. I'm running 41/42, with my own icon theme that I'll be upstreaming to you soon ([vinceliuice/Tela-circle-icon-theme#85](https://github.com/vinceliuice/Tela-circle-icon-theme/pull/85)).
> 
> ![image](https://user-images.githubusercontent.com/17261190/169413308-7d831102-9820-403a-b1ba-f3670be1d390.png)
> 
> (Also, FWIW I use [Floating Dock](https://github.com/fer-moreira/floating-dock) instead of Dash to Dock. Floating Dock works because it's a Dask to Dock fork.)

Wallpaper pls.

**Comment by ran-dall** [comment]
@xukashi That's from Dracula Pro: https://draculatheme.com/pro

**Comment by xukashi** [comment]
> @xukashi That's from Dracula Pro: https://draculatheme.com/pro

Ahhh, ok. Thanks
