### ISSUE TITLE
The theme is not working on Ubuntu 24.04 excpet for some apps

### ISSUE THREAD

**Issue by irtazajawad** [dracula/gtk#288]
I have tried many things (including modifying the .profile file), but none seem to work.

![Tweaks](https://github.com/user-attachments/assets/7db1e0b0-8e1a-4e93-8818-b81cebf42124)

The gtk-master theme is selected even in Gnome Tweaks:

![Files manager](https://github.com/user-attachments/assets/c047906d-a0a2-4288-9214-0384a5f317b4)

It does seem to work on some UI elements e.g. The toolbar and Terminal:

![Toolbar](https://github.com/user-attachments/assets/1e92973f-fa79-40ad-9311-90b332ea3f03)

**Comment by EliverLara** [comment]
**Hi, For the latest versions of Gnome using Gtk4(libadwaita) some extra steps should be done in order to get it working properly, you could do it in two ways:**

1.- Manual way
  - Copy the `assets` folder to the `~/.config` directory
  - Copy the `gtk-4.0/gtk.css` and `gtk-4.0/gtk-dark.css` files to `~/.config/gtk-4.0/`

2.- Using [this script](https://github.com/odziom91/libadwaita-theme-changer) which will copy the needed folders to the right directories

**Comment by irtazajawad** [comment]
Thanks a lot, it started working after reboot:
![updtaed](https://github.com/user-attachments/assets/8941a0ea-3e78-4c23-b6a6-8ef1fb5cfcef)
