### ISSUE TITLE
Software center is transparent ubuntu 20.04

### ISSUE THREAD

**Issue by ruturajjadeja** [dracula/gtk#45]
![Zy8VCUZ](https://user-images.githubusercontent.com/35172163/80173478-dac9a400-85a4-11ea-9777-9dbc9a380335.png)

**Comment by owainharris** [comment]
+1 Same issue here.

**Comment by Belmaj** [comment]
same issue also i love this theme but the software center is super transparent.

**Comment by philipzae** [comment]
This issue happens when the theme isn't found in the gtk-common-themes snap.
https://bugs.launchpad.net/snap-store-desktop/+bug/1867417

**Comment by thiagodff** [comment]
+1 Same issue.

**Comment by sreeramp96** [comment]
![Screenshot from 2020-10-27 22-06-44](https://user-images.githubusercontent.com/16064120/97332808-e45bfd80-18a0-11eb-9ecd-76b42ff032e0.png)
Software center is transparent for me too. Any fix?

**Comment by douglassp** [comment]
![Screenshot from 2020-11-21 13-04-55](https://user-images.githubusercontent.com/29758460/99882021-2bb57f80-2bfc-11eb-8768-bb6359e84b01.png)

This gtk theme hasn't been applied to Ubuntu center here too

**Comment by douglasilvadev** [comment]
Looking for workarounds to solve this problem, I've found this problem is directly related to wrong rendering of the Ubuntu Software (snap-store) reported on their launchpad below:

https://bugs.launchpad.net/snap-store-desktop/+bug/1867417

If you use Gnome Software (sudo apt install gnome-software), the Dracula theme will works fine. 

Cya later!

**Comment by sundbp** [comment]
I scratched my itch and published a snap with the Dracula theme. It can be found here: https://snapcraft.io/dracula-gtk-theme

And the build info is here: https://gitlab.com/sundbp/dracula-theme-snap
